/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/about-page/child': RouteRecordInfo<'/about-page/child', '/about-page/child', Record<never, never>, Record<never, never>>,
    '/activation': RouteRecordInfo<'/activation', '/activation', Record<never, never>, Record<never, never>>,
    '/complaints': RouteRecordInfo<'/complaints', '/complaints', Record<never, never>, Record<never, never>>,
    '/entries': RouteRecordInfo<'/entries', '/entries', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/news': RouteRecordInfo<'/news', '/news', Record<never, never>, Record<never, never>>,
  }
}
